
port = 3270

[servers]
  [servers.g6]
    hostname = "172.16.6.3"
    port = 23
    description = "Gouvernementstraat 6 z/OS instance"
    mnemoric = "G6"
  [servers.example]
    hostname = "example.net"
    port = 23
    description = "Example.net fake entry"
    mnemoric = "SAMPLE"

[users]
  [users.friedkiwi]
    password = "test"
    servers = ["g6", "example"]
    totpkey = "Q3JGOCMWHTEOEZKO2ZOBZUBYPELOOZSI"
  [users.limited]
    password = "password"
    servers = ["example"]
    totpkey = ""